<?xml version="1.0"?>
<package format="3">
  <name>visual_autopick_panel</name>
  <version>0.1.0</version>
  <description>Qt panels (simple and step-by-step) for visual_autopick_ros_ws.</description>
  <maintainer email="laboratorio@example.com">laboratorio</maintainer>
  <license>Apache-2.0</license>

  <depend>rclpy</depend>
  <depend>std_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>cv_bridge</depend>
  <depend>python3-pyqt5</depend>
  <depend>python3-opencv</depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
